[workspace]
resolver = "2"
members = [
    "proto",
    "srv",
    "client/core",
    "client/gui",
    "client/tui",
]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
orbit-proto = { path = "proto" }
orbit-client = { path = "client/core" }
minicbor = { version = "2.3.0", features = ["derive"] }
heapless = { version = "0.9.3" }
